name: CI - Build and Push to Scaleway

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Scaleway Container Registry
        shell: bash
        run: |
          docker login rg.fr-par.scw.cloud/scorimundi-mono -u nologin --password-stdin <<< "${{ secrets.SCALEWAY_SECRET }}"

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: rg.fr-par.scw.cloud/scorimundi-mono/scorimundi-mono:latest
          cache-from: type=gha
          cache-to: type=inline
